Bookkeeping.WebUI/Models/Administration/AgentsViewModel.cs
using Bookkeeping.Data.Models;
using System.Collections.Generic;

namespace Bookkeeping.WebUi.Models
{
    public class AgentsViewModel
    {
        public IList<Agent> Agents { get; set; }
        public string AgentsError { get; set; }
    }
}

Bookkeeping.WebUI/Models/Agent/AgentResolutionViewModel.cs
using System.Web;

namespace Bookkeeping.WebUi.Models
{
    public class AgentResolutionViewModel
    {
        public int Id { get; set; }
        public string Note { get; set; }
        public bool? Decision { get; set; }
        public string PurposeOfPaymentComment { get; set; }
        public HttpPostedFileWrapper ImageFile { get; set; }
        public string ImageData { get; set; }
        public string MimeType { get; set; }
        public string ImageName { get; set; }
        public int TaskId { get; set; }
        public string Inn { get; set; }
        public string PurposeOfPayment { get; set; }
    }
}

Bookkeeping.WebUI/Models/Agent/AgentTaskFilter.cs
using Bookkeeping.Data.Repository.Interfaces;

namespace Bookkeeping.WebUi.Models
{
    public class AgentTaskFilter : AgentTaskFilterViewModel, IAgentTaskFilter
    {
        public int AgentId { get; set; }
    }
}

Bookkeeping.WebUI/Models/Agent/AgentTaskFilterViewModel.cs
namespace Bookkeeping.WebUi.Models
{
    public class AgentTaskFilterViewModel
    {
        public int Offset { get; set; }
        public int Limit { get; set; }
        public bool IsDone { get; set; }
        public string ResolutionError { get; set; }
    }
}

Bookkeeping.WebUI/Models/Agent/AgentTasksViewModel.cs
using Bookkeeping.Data.Models;
using System.Collections.Generic;

namespace Bookkeeping.WebUi.Models
{
    public class AgentTasksViewModel
    {
        public int DoneCount { get; set; }
        public int InWorkCount { get; set; }
        public bool IsDone { get; set; }
        public string ResolutionError { get; set; }
        public string TasksError { get; set; }
        public IList<AgentTask> Tasks { get; set; }
        public int PageSize { get; set; }
    }
}

Bookkeeping.WebUI/Models/Manager/ResolutionViewModel.cs
using Bookkeeping.Data.Models;
using System;

namespace Bookkeeping.WebUi.Models
{
    public class ResolutionViewModel
    {
        public int Id { get; set; }
        public string Note { get; set; }
        public bool? Decision { get; set; }
        public string PurposeOfPaymentComment { get; set; }
        public string ImageData { get; set; }
        public string ImageName { get; set; }
        public string MimeType { get; set; }
        public DateTime? DateResolution { get; set; }
        public Agent Agent { get; set; }
        public DateTime DateTimeDesktopUpdate { get; set; }
        public DateTime DateTimeMobileUpdate { get; set; }
    }
}

Bookkeeping.WebUI/Controllers/AgentController.cs
using Bookkeeping.Common.Exceptions;
using Bookkeeping.Common.Interfaces;
using Bookkeeping.Data.Models;
using Bookkeeping.Data.Models.Identity;
using Bookkeeping.Data.Repository.Interfaces;
using Bookkeeping.WebUi.Models;
using Nelibur.ObjectMapper;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Web.Mvc;
using AgentTask = Bookkeeping.Data.Models.AgentTask;

namespace Bookkeeping.WebUi.Controllers
{
    [BkAuthorize(Roles = UserRoleNames.Agent)]
    public class AgentController : BaseController
    {
        private readonly int _pageSize;
        private readonly ITaskRepository _taskRepository;
        private readonly IResolutionRepository _resolutionRepository;
        private readonly IAgentRepository _agentRepository;

        public AgentController(ITaskRepository taskRepository,
            IAgentRepository agentRepository,
            IResolutionRepository resolutionRepository,
            ISettingsManager settingsManager,
            ILogger logger) : base (logger)
        {
            _taskRepository = taskRepository;
            _resolutionRepository = resolutionRepository;
            _agentRepository = agentRepository;
            _pageSize = settingsManager.GetValue<int>("AgentTasksPageSize");
        }

        [HttpGet]
        public async Task<ActionResult> Tasks(AgentTaskFilterViewModel taskFilter)
        {
            if (taskFilter == null)
            {
                taskFilter = new AgentTaskFilterViewModel();
            }

            if (taskFilter.Offset == 0 && taskFilter.Limit == 0)
            {
                taskFilter.Limit = _pageSize;
            }

            var model = await GetTasksInternal(taskFilter, false);
            model.PageSize = _pageSize;

            return View(model);
        }

        [HttpPost]
        public async Task<JsonResult> GetTasks(AgentTaskFilterViewModel taskFilter)
        {
            return await RunWithResult(async () =>
            {
                var model = await GetTasksInternal(taskFilter, true);
                return new
                {
                    tasksHtml = model.Tasks.Count == 0 && taskFilter.Offset > 0 ? "" : RenderViewToString("_TaskList", model.Tasks),
                    inWorkCount = model.InWorkCount,
                    doneCount = model.DoneCount
                };
            }, "При получении заданий произошла ошибка");
        }

        [HttpGet]
        public async Task<ActionResult> Resolution(int taskId, bool isDone)
        {
            try
            {
                var agentId = await _agentRepository.GetIdByCodeAync(User.Identity.Name);
                var resolution = await _resolutionRepository.GetByTaskAndAgentIdsAsync(taskId, agentId);
                var model = TinyMapper.Map<AgentResolutionViewModel>(resolution);

                return View(model);
            }
            catch (PublicException ex)
            {
                _logger.Error("При получении резолюции произошла ошибка", ex);
                return RedirectToAction("Tasks", new AgentTaskFilterViewModel
                {
                    IsDone = isDone,
                    ResolutionError = ex.Message
                });
            }
            catch (Exception ex)
            {
                var errorMessage = "При получении резолюции произошла ошибка";
                _logger.Error(errorMessage, ex);
                return RedirectToAction("Tasks", new AgentTaskFilterViewModel
                {
                    IsDone = isDone,
                    ResolutionError = errorMessage
                });
            }
        }

        [HttpPost]
        public async Task<JsonResult> SaveResolution(AgentResolutionViewModel model)
        {
            return await RunWithResult(async () =>
            {
                //TODO: validate model
                var now = DateTime.Now;

                var resolution = TinyMapper.Map<Resolution>(model);
                resolution.DateResolution = now;
                resolution.DateTimeMobileUpdate = now;

                if (model.ImageFile != null)
                {
                    using (var reader = new BinaryReader(model.ImageFile.InputStream))
                    {
                        resolution.ImageData = Convert.ToBase64String(reader.ReadBytes(model.ImageFile.ContentLength));
                    }
                    resolution.ImageName = model.ImageFile.FileName;
                    resolution.MimeType = model.ImageFile.ContentType;
                }

                await _resolutionRepository.UpdateResolutionAsync(resolution);

                var urlHelper = new UrlHelper(ControllerContext.RequestContext);
                return urlHelper.Action("Tasks", new AgentTaskFilterViewModel
                {
                    IsDone = true
                });
            }, "При сохранении резолюции произошла ошибка");
        }

        private async Task<AgentTasksViewModel> GetTasksInternal(AgentTaskFilterViewModel filter, bool throwOnError)
        {
            var fullFilter = TinyMapper.Map<AgentTaskFilter>(filter);
            fullFilter.AgentId = await _agentRepository.GetIdByCodeAync(User.Identity.Name);

            try
            {
                var tasks = await _taskRepository.GetListForAgentAsync(fullFilter);
                var inWorkCount = await _taskRepository.GetTaskCountByAgentAsync(fullFilter.AgentId, false);
                var doneCount = await _taskRepository.GetTaskCountByAgentAsync(fullFilter.AgentId, true);

                return new AgentTasksViewModel
                {
                    Tasks = tasks,
                    InWorkCount = inWorkCount,
                    DoneCount = doneCount,
                    IsDone = filter.IsDone,
                    ResolutionError = filter.ResolutionError
                };
            }
            catch (PublicException ex)
            {
                if (throwOnError)
                {
                    throw;
                }
                else
                {
                    _logger.Error("При получении списка заданий для агента произошла ошибка", ex);
                    return new AgentTasksViewModel
                    {
                        Tasks = new List<AgentTask>(),
                        InWorkCount = 0,
                        DoneCount = 0,
                        IsDone = filter.IsDone,
                        ResolutionError = filter.ResolutionError,
                        TasksError = ex.Message
                    };
                }
            }
            catch (Exception ex)
            {
                if (throwOnError)
                {
                    throw;
                }
                else
                {
                    _logger.Error($"При получении списка заданий для агента {fullFilter.AgentId} произошла ошибка", ex);
                    return new AgentTasksViewModel
                    {
                        Tasks = new List<AgentTask>(),
                        InWorkCount = 0,
                        DoneCount = 0,
                        IsDone = filter.IsDone,
                        ResolutionError = filter.ResolutionError,
                        TasksError = "При получении списка заданий для произошла ошибка"
                    };
                }
            }
        }
    }
}

Bookkeeping.WebUI/Views/Agent/Resolution.cshtml
@using Bookkeeping.WebUi.Models;

@model AgentResolutionViewModel

@{
    ViewBag.Title = "Резолюция";
    Layout = "~/Views/Shared/_LayoutAgent.cshtml";
}

<div class="resolution-content">
    @using (Html.BeginForm("SaveResolution", "Agent", FormMethod.Post, new { id = "resolutionForm" }))
    {
        @Html.HiddenFor(p => p.TaskId)
        @Html.HiddenFor(p => p.Id)
        @Html.HiddenFor(p => p.ImageData)
        @Html.HiddenFor(p => p.MimeType)
        @Html.HiddenFor(p => p.ImageName)
        @Html.HiddenFor(p => p.PurposeOfPayment)
        <div class="resolution-content-inner">
            <div class="row resolution-header @(Model.Decision.HasValue ? (Model.Decision.Value ? "green" : "red") : "")">
                <div class="back-btn" data-location="@Url.Action("Tasks", "Agent")">
                    <span class="glyphicon glyphicon-arrow-left back-icon"></span>
                </div>
                <span class="title-text">@Model.Inn</span>
            </div>
            <div class="row resolution-body">
                <div class="row resolution-image-upload-wrap">
                    <input class="hidden" type="file" id="image"/>
                    <div class="resolution-image">
                        <div class="preview" @Html.Raw(string.IsNullOrEmpty(Model.ImageData) ? "style='display: none;'" : "")>
                            <img class="image" src="@(string.IsNullOrEmpty(Model.ImageData) ? "" : $"data:{Model.MimeType};base64,{Model.ImageData}")" />
                            <div class="remove-image-icon">
                                <img src="~/Content/images/x-icon-white.svg" />
                            </div>
                        </div>
                        <div class="row resolution-image-upload-icon" @Html.Raw(string.IsNullOrEmpty(Model.ImageData) ? "" : "style='display: none;'")>
                            <img src="~/Content/images/upload-icon-white.svg" />
                        </div>
                    </div>
                </div>

                <div class="row resolution-info">
                    <div class="row resolution-buttons">
                        @Html.HiddenFor(p => p.Decision)
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 resolution-btn-wrap resolution-btn-ok-wrap">
                            <div class="row resolution-btn resolution-ok-btn @(Model.Decision.HasValue && !Model.Decision.Value ? "gray" : "")">
                                <span class="glyphicon glyphicon-ok resolution-btn-icon"></span>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 resolution-btn-wrap resolution-btn-deny-wrap">
                            <div class="row resolution-btn resolution-deny-btn @(Model.Decision.HasValue && Model.Decision.Value ? "gray" : "")">
                                <span class="glyphicon glyphicon-remove-circle resolution-btn-icon"></span>
                            </div>
                        </div>
                    </div>

                    @{
                        Html.RenderPartial("_TextAreaMaterial", new TextInputViewModel {
                            Id = "Note",
                            Value = Model.Note,
                            FullLabelText = "Примечание",
                            ShortLabelText = "Примечание",
                            IsRequired = false
                        });
                    }

                    @if(!string.IsNullOrEmpty(Model.PurposeOfPayment))
                    {
                        <div class="purpose-of-payment-comment">
                            <div class="purpose-of-payment">
                                <div class="purpose-of-payment-title">Необходимо проверить назначение платежа!</div>
                                <div class="purpose-of-payment-text">@Model.PurposeOfPayment</div>
                            </div>
                        </div>

                        Html.RenderPartial("_TextAreaMaterial", new TextInputViewModel {
                            Id = "PurposeOfPaymentComment",
                            Value = Model.PurposeOfPaymentComment,
                            FullLabelText = "Комментарий к назначению",
                            ShortLabelText = "Комментарий к назначению",
                            IsRequired = true
                        });
                    }
                </div>
            </div>
        </div>
    }
</div>

<div class="row resolution-footer">
    <div class="row save-btn @(Model.Decision.HasValue ? "" : "gray")">
        <span class="save-btn-text">СОХРАНИТЬ</span>
    </div>
</div>

@section scripts {
    <script>
        var saveResolutionUrl = '@Url.Action("SaveResolution", "Agent")';
    </script>
    @Scripts.Render("~/bundles/agent-resolution")
}

Bookkeeping.WebUI/Views/Agent/Tasks.cshtml
@using Bookkeeping.WebUi.Models
@using Bookkeeping.Data.Models

@model AgentTasksViewModel

@{
    ViewBag.Title = "Задачи";
    Layout = "~/Views/Shared/_LayoutAgent.cshtml";
}

<nav class="navbar navbar-inverse mobile">
    <div class="navbar-controls mobile row">
        <div class="navbar-title mobile text-center">
            <div class="row title-tabs">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 title-tab in-work @(Model.IsDone ? "" : "active")"><a href="#">В работу&nbsp;<span class="numberCircle @(@Model.InWorkCount == 0 ? "empty" : "")">@Model.InWorkCount</span></a></div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 title-tab is-done @(Model.IsDone ? "active" : "")"><a href="#">Готово&nbsp;<span class="numberCircle @(@Model.DoneCount == 0 ? "empty" : "")">@Model.DoneCount</span></a></div>
            </div>
        </div>
        <div class="navbar-account mobile">
            <span class="glyphicon glyphicon-log-in log-out-icon"></span>
        </div>
    </div>
</nav>

<div class="row mobile-task-list-wrap">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 task-list mobile">
        @{Html.RenderPartial("_TaskList", Model.Tasks);}
    </div>
</div>

<div class="no-tasks-wrap" style="display: @(Model.Tasks.Any() ? "none" : "table")">
    <div class="no-tasks">
        <div class="row no-tasks-inner">
            <div class="col-lg-4 col-md-4 hidden-sm hidden-xs"></div>
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <div class="no-done-tasks" style="display: @(Model.IsDone ? "block" : "none")">
                    <span class="no-tasks-text">Нет выполненных заданий</span>
                </div>
                <div class="no-new-tasks" style="display: @(Model.Tasks.Any() ? "none" : "block")">
                    <span class="no-tasks-text">Новых заданий нет</span>
                    <button class="btn no-tasks-btn no-new-tasks-btn">ОБНОВИТЬ</button>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 hidden-sm hidden-xs"></div>
        </div>
    </div>
</div>



@section scripts {
    <script>
        var getTasksUrl = '@Url.Action("GetTasks", "Agent")';
        var saveResolutionUrl = '@Url.Action("SaveResolution", "Agent")';
        var pageSize = @Model.PageSize;

        @Html.Raw(string.IsNullOrEmpty(Model.ResolutionError) ? "" : $"onError('{Model.ResolutionError}');")
        @Html.Raw(string.IsNullOrEmpty(Model.TasksError) ? "" : $"onError('{Model.TasksError}');")
    </script>
    @Scripts.Render("~/bundles/agent-tasks")
}

Bookkeeping.WebUI/Views/Agent/_TaskList.cshtml
@using Bookkeeping.Data.Models;

@model IList<AgentTask>

@*todo: simplify model, remove unused properties*@

@foreach (var task in Model)
{
    <div class="panel panel-default mobile-task-item" data-location="@Url.Action("Resolution", "Agent", new { taskId = task.Id, isDone = task.Decision.HasValue })">
        <div class="row task-info">
            <div class="task-main-info col-lg-10 col-md-10 col-sm-10 col-xs-10">
                <div class="row task-date">
                    @task.Date.ToString("dd.MM.yyyy HH:mm")
                </div>
                <div class="row task-inn">
                    @task.Inn
                </div>
            </div>
            <div class="task-decision row col-lg-2 col-md-2 col-sm-2 col-xs-2">
                @if (task.Decision.HasValue)
                {
                    <div class="task-decision-icon">
                        <span class="glyphicon @(task.Decision.Value ? "decision-ok glyphicon-ok" : "decision-deny glyphicon-remove-circle")"></span>
                    </div>
                }
            </div>
        </div>
    </div>
}